name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: terms
    attributes:
      label: Contributor License Agreement
      description: Make sure to read and accept the CLA, before you open the bug. Tick the checkbox in case you accept it.
      options:
        - label: I have read and accept the [Contributor License Agreement](https://github.com/porscheofficial/oss-docs/blob/67c5b24838a293ce7a964884e6005eb71f2b8579/CONTRIBUTOR_LICENSE_AGREEMENT.md)
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: framework
    attributes:
      label: Framework
      placeholder: e.g. React
    validations:
      required: true
  - type: input
    id: pds-version
    attributes:
      label: Porsche Design System version
      placeholder: e.g. 2.16.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: input
    id: browser-version
    attributes:
      label: Browser version
      placeholder: e.g. 106.0.5249.119
    validations:
      required: false
  - type: input
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) of the issue using [StackBlitz](https://designsystem.porsche.com/latest/help/bug-report#reproduction).
      placeholder: e.g. https://stackblitz.com/
    validations:
      required: true
 - type: textarea
    id: description
    attributes:
      label: Steps to reproduce the behavior
      description: A clear and concise description of what the bug is
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error'
      validations:
    required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
